server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import:
      - classpath:kafka-config.yaml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  main:
    banner-mode: off

  application:
    name: kafka-example

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/example}
    username: ${SPRING_DATASOURCE_USERNAME:example}
    password: ${SPRING_DATASOURCE_PASSWORD:example}
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      add-mappings: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:DEBUG}
        kafka.transaction: DEBUG
        kafka: DEBUG
        transaction: TRACE
      apache:
        orm:
          jpa:
            JpaTransactionManager: trace
        kafka:
          transaction: trace
          listener:
            KafkaMessageListenerContainer: error
